/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alejandro' at '9/12/16 9:31' with Gradle 3.2.1
 *
 * @author alejandro, @date 9/12/16 9:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
